/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VBtn: typeof import('vuetify/lib')['VBtn']
    VBtnToggle: typeof import('vuetify/lib')['VBtnToggle']
    VHover: typeof import('vuetify/lib')['VHover']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemActionText: typeof import('vuetify/lib')['VListItemActionText']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTiptapEditor: typeof import('./src/components/VTiptapEditor.vue')['default']
    VTiptapNodeViewWrapper: typeof import('./src/components/VTiptapNodeViewWrapper.vue')['default']
    VTiptapTippy: typeof import('./src/components/VTiptapTippy.vue')['default']
    VTiptapToolbar: typeof import('./src/components/VTiptapToolbar.vue')['default']
  }
}
